name: Attendance Management System
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  laravel-tests:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20        
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: |
        composer install
    - name: Run
      shell: bash
      run: |
        "/c/Program Files/7-Zip/7z.exe" a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m ams.tar.gz . -x!public
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ams.*
        tag_name: ${{ github.event.inputs.tags }}
